### ISSUE TITLE
a bug in the docs

### ISSUE THREAD

**Issue by RustyYato** [matklad/drop_bomb#3]
In the notes section of the crate docs

> When #[cfg(debug_assertions)] is enabled, DebugDropBomb is an always defused and has a zero size.

Which should be

> When #[cfg(debug_assertions)] is disabled, DebugDropBomb is an always defused and has a zero size.

or 

> When #[cfg(not(debug_assertions))] is enabled, DebugDropBomb is an always defused and has a zero size.

**Comment by matklad** [comment]
Fixed in #2
